AXF/AXF/AXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('App.urls', namespace='App')),
    # url(r'^/$', 'App.urls.home'),

]

AXF/AXF/App/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^home/$', home, name='home'),

    url(r'^market/$', market, name='market'),
    url(r'^marketwithparams/(\d+)/(\d+)/(\d+)/$', market_with_params, name='market_with_params'),

    url(r'^mine/$', mine, name='mine'),
    url(r'^register/$', register, name='register'),
    url(r'registerhandle/$', register_handle, name='register_handle'),
    url(r'^checkusername/$', check_username, name='check_username'),
    url(r'^logout/$', logout, name='logout'),

    url(r'^login/$', login, name='login'),
    url(r'^loginhandle/$', login_handle, name='login_handle'),
    url(r'^cart/$', cart, name='cart'),

    url(r'^addtocart/$', add_to_cart, name='add_to_cart'),
    url(r'^addnum/$', add_num, name='add_num'),
    url(r'^reducenum/$', reduce_num, name='reduce_num'),
    url(r'^deletecart/$', delete_cart, name='deltet_cart'),
    url(r'^cartselect/$', cart_select, name='cart_select'),
    url(r'^cartselectall/$', cart_selectall, name='cart_selectll'),

    url(r'^orderadd/$',order_add,name='order_add'),
    url(r'^order/(\d+)/$', order, name='order'),
    url(r'^orderchangestatus/$', order_change_status, name='order_change_status'),
    url(r'^orderwaitpay/$', order_waitpay, name='order_waitpay'),
    url(r'^orderpaid/$', order_paid, name='order_paid'),
    url('^topaid/$',to_paid,name='to_paid'),
    url('^cancelpaid/$',cancel_paid,name='cancel_paid'),

    url(r'^getpwd/$',getpwd,name='gepwd')
]

AXF/AXF/templates/market/market.html
{% extends 'base_main.html' %}
{% load static %}
{% block title %}
    闪购
{% endblock %}
{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'app/market/market.css' %}">
{% endblock %}

{% block extJS %}
    <script src="{% static 'app/market/market.js' %}"></script>
{% endblock %}


{% block content %}
    <div id="market">

        {# 左侧的主分类 #}
        <aside>
            <ul>
                {% for foodtype in foodtypes %}
                <li>
                    <a href="{% url 'App:market_with_params' foodtype.typeid '0' '0' %}">{{ foodtype.typename }}</a>
                    {% if typeid == foodtype.typeid %}
                        <div class="yellowSlide"></div>
                    {% endif %}
                </li>
                {% endfor %}
            </ul>
        </aside>

        {# 右侧 #}
        <section>

            {# 导航nav #}
            <nav>
                <ul>
                    <li id="child_type">
                        <span>
                            全部类型 <span id="child_type_icon" class="glyphicon glyphicon-chevron-down"></span>
                        </span>
                    </li>
                    <li id="sort_rule">
                        <span>
                            综合排序 <span id="sort_rule_icon" class="glyphicon glyphicon-chevron-down"></span>
                        </span>
                    </li>
                </ul>
            </nav>


            {# 商品 #}
            <menu>
                <ul>
                    {% for goods in goods_list %}
                        <li>
                            <a href="#">
                                <img src="{{ goods.productimg }}" />
                                <div class="shoppingInfo">
                                    <h6>{{ goods.productlongname }}</h6>
                                    <p class="detailTag">
                                        <span>精选</span>
                                    </p>
                                    <p class="unit">{{ goods.specifics }}</p>
                                    <p class="price">
                                        <span> ¥{{ goods.price }}</span>
                                        <s> ¥{{ goods.marketprice }}</s>
                                    </p>
                                </div>
                            </a>

                        <section>
                                <button class="reduce">-</button>
                                <span class="number">1</span>
                                <button class="add">+</button>
                        </section>
                        <button goodsid="{{ goods.id }}" class="addtocart">加入购物车</button>

                        </li>
                    {% endfor %}
                </ul>


                {# 子分类数据 #}
                <div id="child_type_container">
                    <div>
                        {% for child_type in child_type_list %}
                            <a href="{% url 'App:market_with_params' typeid child_type.1 '0' %}">
                                <span>{{ child_type.0 }}</span>
                            </a>
                        {% endfor %}
                    </div>
                </div>

                {# 排序规则 #}
                <div id="sort_rule_container">
                    <div>
                        <a href="{% url 'App:market_with_params' typeid typechildid '0' %}">
                            <span>综合排序</span>
                        </a>
                        <a href="{% url 'App:market_with_params' typeid typechildid '1' %}">
                            <span>销量排序</span>
                        </a>
                        <a href="{% url 'App:market_with_params' typeid typechildid '2' %}">
                            <span>价格降序</span>
                        </a>
                        <a href="{% url 'App:market_with_params' typeid typechildid '3' %}">
                            <span>价格升序</span>
                        </a>
                    </div>
                </div>

            </menu>



        </section>




    </div>
{% endblock %}